POTENTIAL_TO_COLLECT_COIN = 'POTENTIAL_TO_COLLECT_COIN'
POTENTIAL_TO_NOT_COLLECT_COIN = 'POTENTIAL_TO_NOT_COLLECT_COIN'

POTENTIAL_TO_DIE_BY_BOMB = 'POTENTIAL_TO_DIE_BY_BOMB'
POTENTIAL_TO_NOT_DIE_BY_BOMB = 'POTENTIAL_TO_NOT_DIE_BY_BOMB'

POTENTIAL_TO_DIE_BY_EXPLOSION = 'POTENTIAL_TO_DIE_BY_EXPLOSION'
POTENTIAL_TO_NOT_DIE_BY_EXPLOSION = 'POTENTIAL_TO_NOT_DIE_BY_EXPLOSION'

POTENTIAL_TO_EXPLODE_CRATE = 'POTENTIAL_TO_EXPLODE_CRATE'
POTENTIAL_TO_NOT_EXPLODE_CRATE = 'POTENTIAL_TO_NOT_EXPLODE_CRATE'

DROPPED_BOMB_NEAR_CRATE = 'DROPPED_BOMB_NEAR_CRATE'

ITERATION_PENALTY = 'ITERATION_PENALTY'
